// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_net_lab.DAL;

#nullable disable

namespace asp_net_lab.Migrations
{
    [DbContext(typeof(FilmyContext))]
    partial class FilmyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("asp_net_lab.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Cena")
                        .HasColumnType("real");

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rezyser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Filmy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cena = 39.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 1,
                            Opis = "amerykański dramat obyczajowy z 1997 roku w reżyserii Gusa Van Santa, nagrodzony dwoma Oscarami: za najlepszy scenariusz stworzony przez Bena Afflecka i Matta Damona i najlepszą rolę drugoplanową – psychoterapeuty Seana Maguire'a, w którego wcielił się Robin Williams.",
                            Rezyser = "Gus Van Sant",
                            Tytul = "Buntownik z wyboru"
                        },
                        new
                        {
                            Id = 2,
                            Cena = 24.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 6,
                            Opis = "amerykański film kryminalny z 1994 roku w reżyserii Quentina Tarantino, oparty na scenariuszu Tarantino i Rogera Avary’ego. Film, w którym występują John Travolta, Samuel L. Jackson, Bruce Willis, Tim Roth, Ving Rhames i Uma Thurman, opowiada kilka epizodów rozgrywających się w przestępczym Los Angeles.",
                            Rezyser = "Quentin Tarantino",
                            Tytul = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Cena = 40.5f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 5,
                            Opis = "apoński film animowany w reżyserii Hayao Miyazakiego, wyprodukowany przez Studio Ghibli. Jego japońska premiera miała miejsce 14 lipca 2023 r. Polska premiera kinowa miała miejsce 19 stycznia 2024 r.",
                            Rezyser = "Hayao Miyazaki",
                            Tytul = "Chłopiec i Czapla"
                        },
                        new
                        {
                            Id = 4,
                            Cena = 59.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 2,
                            Opis = "amerykańsko-kanadyjski film science fiction z 2021 roku w reżyserii Denisa Villeneuve’a, zrealizowany na podstawie powieści Franka Herberta o tym samym tytule, adaptujący jej pierwszą połowę; zdobył sześć Oscarów. Film zadebiutował 3 września 2021 w ramach 78. MFF w Wenecji.",
                            Rezyser = "Denis Villeneuve",
                            Tytul = "Diuna 1"
                        },
                        new
                        {
                            Id = 5,
                            Cena = 64.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 2,
                            Opis = "amerykańsko-kanadyjski film science fiction z 2024 roku w reżyserii Denisa Villeneuve’a. Druga część ekranizacji powieści Franka Herberta o tym samym tytule, bezpośrednia kontynuacja filmu z 2021 roku. Film zadebiutował 6 lutego 2024 w Auditorio Nacional w mieście Meksyk.",
                            Rezyser = "Denis Villeneuve",
                            Tytul = "Diuna 2"
                        },
                        new
                        {
                            Id = 6,
                            Cena = 29.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 1,
                            Opis = "amerykański film gangsterski z 1972 roku w reżyserii Francisa Forda Coppoli, z Marlonem Brando i Alem Pacino w rolach głównych. Adaptacja powieści Mario Puzo o tym samym tytule. Film opowiada historię rodziny Corleone, potężnego klanu mafijnego z Nowego Jorku, w latach 1945–1955.",
                            Rezyser = "Francis Ford Coppola",
                            Tytul = "Ojciec chrzestny"
                        },
                        new
                        {
                            Id = 7,
                            Cena = 24.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 1,
                            Opis = "amerykański dramat filmowy z 1994 roku w reżyserii Franka Darabonta, oparty na opowiadaniu Stephena Kinga 'Rita Hayworth and Shawshank Redemption' z 1982 roku. W rolach głównych wystąpili Tim Robbins i Morgan Freeman. Film opowiada historię Andy'ego Dufresne'a (Robbins), niesłusznie skazanego za morderstwo i wysłanego do więzienia Shawshank.",
                            Rezyser = "Frank Darabont",
                            Tytul = "Skazani na Shawshank"
                        },
                        new
                        {
                            Id = 8,
                            Cena = 39.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 7,
                            Opis = "amerykański film fantasy z 2001 roku w reżyserii Petera Jacksona, oparty na powieści J.R.R. Tolkiena 'Władca Pierścieni: Drużyna Pierścienia' z 1954 roku. Jest to pierwszy film z trylogii 'Władca Pierścieni'. W filmie wystąpili Elijah Wood, Ian McKellen, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Bernard Hill, Christopher Lee, Billy Boyd, Dominic Monaghan, Orlando Bloom, Hugo Weaving i Ian Holm.",
                            Rezyser = "Peter Jackson",
                            Tytul = "Władca Pierścieni: Drużyna Pierścienia"
                        },
                        new
                        {
                            Id = 9,
                            Cena = 29.9f,
                            DataDodania = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KategoriaId = 3,
                            Opis = "amerykański film komediowo-dramatyczny z 1994 roku w reżyserii Roberta Zemeckisa, oparty na powieści Winstona Grooma 'Forrest Gump' z 1986 roku. W filmie wystąpił Tom Hanks jako Forrest Gump, mężczyzna o niskim IQ, który staje się świadkiem i uczestnikiem wielu kluczowych wydarzeń w historii XX wieku. Film zdobył sześć Oscarów, w tym za najlepszy film i najlepszego aktora dla Hanksa.",
                            Rezyser = "Robert Zemeckis",
                            Tytul = "Forrest Gump"
                        });
                });

            modelBuilder.Entity("asp_net_lab.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Dramat",
                            Opis = "Filmy o poważnej tematyce, często poruszające trudne i emocjonalne kwestie."
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Science fiction",
                            Opis = "Filmy o tematyce fantastyczno-naukowej, często rozgrywające się w przyszłości lub w innych światach."
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Komedia",
                            Opis = "Filmy o charakterze humorystycznym, mające na celu rozśmieszyć widza."
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Horror",
                            Opis = "Filmy mające na celu wzbudzić strach i napięcie u widza."
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "Animowane",
                            Opis = "Filmy rysunkowe lub komputerowe, przeznaczone dla dzieci i dorosłych."
                        },
                        new
                        {
                            Id = 6,
                            Nazwa = "Kryminał",
                            Opis = "Filmy dotyczące przestępstw, śledztw i wymiaru sprawiedliwości."
                        },
                        new
                        {
                            Id = 7,
                            Nazwa = "Fantasy",
                            Opis = "Filmy zawierające elementy magiczne, mityczne stworzenia, nadprzyrodzone światy."
                        });
                });

            modelBuilder.Entity("asp_net_lab.Models.Film", b =>
                {
                    b.HasOne("asp_net_lab.Models.Kategoria", "Kategoria")
                        .WithMany("Filmy")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("asp_net_lab.Models.Kategoria", b =>
                {
                    b.Navigation("Filmy");
                });
#pragma warning restore 612, 618
        }
    }
}
